spring:
  datasource:
    username: ${db.username}
    hikari:
      maximum-pool-size: ${db.maximum-pool-size}
      connection-timeout: ${db.connection-timeout}
    url: ${db.url}
    password: ${db.password}
  application:
    name: product-msv
  profiles:
    default: default
  config:
    import: "optional:configserver:http://localhost:7777"
#  datasource:
#    url: jdbc:postgresql://localhost:5432/companies
#    username: mramos
#    password: academyjava
#    hikari:
#      connection-timeout: 20000
#      maximum-pool-size: 5
server:
  servlet:
    context-path: /product-msv
  port: 0
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}}"
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
